### ISSUE TITLE
Jumping issues and impressions.

### ISSUE THREAD

**Issue by ghost** [EamonnMR/Flythrough.Space#28]
When I jump, the engine flare of my ship disappears. 

When I press escape, I don't see the map immediately. There's just a green circle for the current system. I have to click and drag before the map appears. [image](https://i.imgur.com/9wtuo48.png)

In an empty system, I still have to move out from the center of the system to jump. There's no indicator for when the ship is ready to jump either, and in an empty system with no starfield, no planets and no engine flare, it looks like nothing is happening.

There's no animation for jumping. Anything would be appreciated here.

It's super disorienting to have planets and ships rapidly get larger or smaller when you fly around them.

It would be nice to have a way to reload your save from inside the game, since getting stranded is a normal experience. [image](https://i.imgur.com/1Dl1Sn6.png)

**Comment by EamonnMR** [comment]
Thanks for taking the time to write a report. I think the following is a list of specific features which should address these problems:
* Leaving the gameplay state (dying or jumping) breaks particle systems
* Add Jumping animation
* Popups / text to indicate that you can't jump from a system ("You are too close to the mass shadow of nearby stellar-scale objects. Move to flat space to spin up sidereal drive")
* Allow jumping from the center of empty systems (maybe even systems that only have small objects, like stations or asteroids)
* Optional ortho camera mode to get rid of perspective (size changes when things go up and down the screen (I'm about to merge a PR to add a settings menu.)
* Implement save/load
* Option to return to main menu from inside game

**Comment by EamonnMR** [comment]
Oh and a starfield. I just merged a change which adds a starfield. And Makin an optional bird's-eye camera might be a decent quick-fix for the perspective issue-turns out Ortho cams are a bit more work (the ships would render out of perspective which won't look good. A fix would be to add a vertex shader which fakes perspective but I'm just not that good-as you can see from the attempt at a shader starfield before I did the sprite one!)

**Comment by EamonnMR** [comment]
I think everything mentioned here is actually fixed now!
